move miniconda_installer to defaults (so it can be overriden in group_vars etc)
uchida/ansible-miniconda-role pull request #14
Opened 2017-09-14 16:16 UTC by lhoss

a redo of https://github.com/uchida/ansible-miniconda-role/pull/4/files
with a small change that I added it into the defaults before the var `miniconda_installer_checksum`

Finally I've another reason (where I see no other solution), to overwrite that var:
* ensure that the a Miniconda2* installer is used when `miniconda_python: 2` is set, independent of some hard-to-understand depending variable `miniconda_oldversions` 

( ps: more PRs coming. I extra decided to make 1 per small feature, with the hope of getting stuff merged upstream 👍 )

2018-02-26 11:10 UTC, lhoss commented
ping
@uchida you are still maintaining your miniconda role?  (else will just care to open PRs to our company's fork)

2018-02-26 11:14 UTC, uchida commented
Oh, sorry for forgetting, I'll review PR soon.

2018-02-26 11:18 UTC, uchida requested changes
please add about the `miniconda_installer` variable to README.md

2018-02-27 14:17 UTC, uchida approved these changes

2018-02-27 14:17 UTC, merged